### PR TITLE
Add ICESugar Board Support Package

### PR DESCRIPTION
**Pull request by XxChang**
early phase

### CODE REVIEW

**Comment by samitbasu** [comment]
This is awesome!  Do you want to just publish the crate directly to `crates.io`?  I don't have an ICESugar, so I can't test it.

**Comment by XxChang** [comment]
Nice! Thanks for your advice.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Samit Basu ***@***.***>
发送时间: Saturday, April 15, 2023 8:35:14 AM
收件人: samitbasu/rust-hdl ***@***.***>
抄送: chang xu ***@***.***>; Author ***@***.***>
主题: Re: [samitbasu/rust-hdl] Add ICESugar Board Support Package (PR #18)


This is awesome! Do you want to just publish the crate directly to crates.io? I don't have an ICESugar, so I can't test it.

―

**Comment by samitbasu** [comment]
@XxChang  - I'm going to close this on the assumption you will publish directly to crates.io.  LMK if you need anything further from me.  And thanks for the contribution!

**Comment by XxChang** [comment]
It’ok ,thanks

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Samit Basu ***@***.***>
发送时间: Sunday, July 2, 2023 2:28:09 AM
收件人: samitbasu/rust-hdl ***@***.***>
抄送: chang xu ***@***.***>; Mention ***@***.***>
主题: Re: [samitbasu/rust-hdl] Add ICESugar Board Support Package (PR #18)


@XxChang<https://github.com/XxChang> - I'm going to close this on the assumption you will publish directly to crates.io. LMK if you need anything further from me. And thanks for the contribution!

―

**Comment by andelf** [comment]
@samitbasu  Are there any sections on README or docs for a list of third-party bsp packages?
I'm trying to implement Gowin support.

**Pull request closed without merging**
